config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get "admin", to: redirect("admin/entries")
  namespace :admin do
    resources :entries, only: %i[ index new edit create update destroy ]
    resources :media_items, only: %i[ index create destroy ]
    resources :tags
  end

  get "/feed", to: "feeds#show", defaults: { format: "atom" }
  resources :entries, only: %i[ index ] do
    resources :comments, only: %i[ create destroy ], shallow: true
  end
  get "/:slug", to: "entries#show", as: :entry_slug
  resource :session

  # Defines the root path route ("/")
  root "entries#index"
end

app/models/media_item.rb
class MediaItem < ApplicationRecord
  has_one_attached :media
end

app/controllers/admin/media_items_controller.rb
class Admin::MediaItemsController < ApplicationController
  before_action :set_media_item, only: %i[ destroy ]

  def index
    @media_items = MediaItem.order(created_at: :desc)
    @media_item = MediaItem.new
  end

  def create
    @media_item = MediaItem.new(media_item_params)

    if @media_item.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to admin_media_items_path, notice: "Media item was successfully created." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    if @media_item.destroy
      flash[:notice] = "Media item was successfully destroyed."
    else
      flash[:alert] = "An error occurred: media item couldn't be destroyed."
    end

    redirect_to admin_media_items_path
  end

  private
    def media_item_params
      params.expect(media_item: [ :media ])
    end

    def set_media_item
      @media_item = MediaItem.find(params[:id])
    end

    def hide_delete?
      params[:hide_delete].present?
    end
    helper_method :hide_delete?

    def media_item_target
      params[:target]
    end
    helper_method :media_item_target
end

app/views/admin/media_items/_form.html.erb
<%= form_with(model: [:admin, media_item], id: "media-items-form", class: "media-items__form") do |form| %>

  <%= hidden_field_tag :hide_delete, params[:hide_delete] if params[:hide_delete].present? %>
  <%= hidden_field_tag :target, params[:target] if params[:target].present? %>

  <%= form.file_field :media %>
  <%= form.submit %>
<% end %>

app/views/admin/media_items/_media_item.html.erb
<div class="media-item__thumb">
  <% if item.media.representable? %>
    <%= image_tag item.media.representation(resize_to_fill: [150, 150]),
          data: { controller: "media-item", action: "click->media-item#embed", "media-item-target-value": media_item_target }%>
  <% else %>
    <p>This image cannot be represented.</p>
  <% end %>

  <% unless hide_delete? %>
    <%= button_to "Eliminar", admin_media_item_path(item), method: :delete, data: { turbo_confirm: "Are you sure?" } %>
  <% end %>
</div>

app/views/admin/media_items/create.turbo_stream.erb
<%= turbo_stream.replace "media-items-form" do %>
  <%= render partial: "form", locals: { media_item: MediaItem.new } %>
<% end %>

<%= turbo_stream.prepend "media-items" do %>
  <%= render partial: "media_item", locals: { item: @media_item, media_item_target: media_item_target } %>
<% end %>

app/views/admin/media_items/index.html.erb
<% content_for :title, "Admin: Media" %>

<%= turbo_frame_tag "media-items-page" do %>
  <%= render "form", media_item: @media_item %>

  <div id="media-items" class="media-items">
    <% @media_items.each do |item| %>
      <%= render partial: "media_item", locals: { item: } %>
    <% end %>
  </div>
<% end %>