config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get "admin", to: redirect("admin/entries")
  namespace :admin do
    resources :entries, only: %i[ index new edit create update destroy ]
    resources :media_items, only: %i[ index create destroy ]
    resources :tags
  end

  get "/feed", to: "feeds#show", defaults: { format: "atom" }
  resources :entries, only: %i[ index ] do
    resources :comments, only: %i[ create destroy ], shallow: true
  end
  get "/:slug", to: "entries#show", as: :entry_slug
  resource :session

  # Defines the root path route ("/")
  root "entries#index"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :entries, through: :taggings

  default_scope { order(:name) }

  validates :name, presence: true
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < AdminController
  before_action :set_tag, only: %i[ edit update destroy ]

  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def edit
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to admin_tags_path, notice: "Etiqueta añadida con éxito."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @tag.update(tag_params)
      redirect_to admin_tags_path, notice: "Etiqueta editada con éxito", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @tag.destroy!
    redirect_to admin_tags_path, notice: "Etiqueta eliminada con éxito", status: :see_other
  end

  private
    def set_tag
      @tag = Tag.find(params.expect(:id))
    end

    def tag_params
      params.expect(tag: [ :name ])
    end
end

app/views/admin/tags/_form.html.erb
<%= form_with(model: [:admin, tag]) do |form| %>
  <div class="input-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "input" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/tags/edit.html.erb
<% content_for :title, "Editar etiqueta" %>

<h1>Editar etiqueta</h1>

<%= render "form", tag: @tag %>

app/views/admin/tags/index.html.erb
<% content_for :title, "Admin: Tags" %>

<p><%= link_to "Añadir etiqueta", new_admin_tag_path %></p>

<table id="tags" class="table">
  <thead>
    <tr>
      <td>Name</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= link_to tag.name, edit_admin_tag_path(tag) %></td>
        <td><%= button_to "Eliminar", admin_tag_path(tag), method: :delete, data: { turbo_confirm: "¿Seguro que quieres eliminar esta etiqueta (#{tag.name})?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/tags/new.html.erb
<% content_for :title, "Nueva etiqueta" %>

<h1>Nueva etiqueta</h1>

<%= render "form", tag: @tag %>