config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get "admin", to: redirect("admin/entries")
  namespace :admin do
    resources :entries, only: %i[ index new edit create update destroy ]
    resources :media_items, only: %i[ index create destroy ]
    resources :tags
  end

  get "/feed", to: "feeds#show", defaults: { format: "atom" }
  resources :entries, only: %i[ index ] do
    resources :comments, only: %i[ create destroy ], shallow: true
  end
  get "/:slug", to: "entries#show", as: :entry_slug
  resource :session

  # Defines the root path route ("/")
  root "entries#index"
end

app/models/entry.rb
class Entry < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  before_validation :set_slug
  before_validation :set_body_html

  validates :title, presence: true

  scope :published, -> { where(draft: false).where("published_at < ?", Time.current) }

  scope :filter_by_tags, ->(tags) {
    tag_names = Array.wrap(tags)

    return all unless tag_names.any?

    joins(:tags)
      .where(tags: { name: tag_names })
      .group(:id)
      .having(
        Tag.arel_table[:id].count(true).eq(tag_names.size)
      )
  }

  def status
    return "draft" if draft
    return "scheduled" if published_at > Time.current
    "published"
  end

  private

    def set_body_html
      extensions = %i[ fenced_code_blocks]

      html = Markdown.new(body_markdown, *extensions).to_html

      self.body_html = set_img_srcset(html)
    end

    def set_slug
      return if self.slug.present?

      self.slug = title.parameterize
    end

    def set_img_srcset(html)
      doc = Nokogiri::HTML.fragment(html)
      doc.css("img").each { |img| replace_image(img, doc) }
      doc.to_html
    end

    def replace_image(img, doc)
      blob = image_blob(img["src"])

      variant = blob.representation(resize_to_limit: [ 800, 800 ])
      new_image_url = Rails.application.routes.url_helpers.rails_blob_url(variant, only_path: true)
      new_image = ActionController::Base.helpers.image_tag(new_image_url, alt: img["alt"])

      img.replace(new_image)
    end

    def image_blob(url)
      uri = URI.parse(url)

      return unless uri.path.start_with?("/rails/active_storage/representations/redirect")

      segments = uri.path.split("/")
      signed_id = segments[5..-1][0]

      return unless signed_id

      ActiveStorage::Blob.find_signed(signed_id)
    end
end

app/controllers/admin/entries_controller.rb
module Admin
  class EntriesController < AdminController
    before_action :set_entry_from_id, only: %i[ edit update destroy ]

    def index
      @entries = Entry.order(published_at: :desc)
    end

    def show
    end

    def new
      @entry = Entry.new
    end

    def edit
    end

    def create
      @entry = Entry.new(entry_params)

      if @entry.save
        redirect_to edit_admin_entry_path(@entry), notice: "Entry was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @entry.update(entry_params)
        redirect_to admin_entry_path(@entry), notice: "Entry was successfully updated.", status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @entry.destroy!
      redirect_to admin_entries_path, notice: "Entry was successfully destroyed.", status: :see_other
    end

    private
      def set_entry_from_id
        @entry = Entry.find(params.expect(:id))
      end

      def set_entry_from_slug
        @entry = Entry.find_by_slug(params[:slug])
      end

      def entry_params
        params.expect(entry: [ :title, :slug, :published_at, :draft, :body_markdown, tag_ids: [] ])
      end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show ]

  PER_PAGE = 5.freeze

  def index
    @entries = Entry
                .published
                .filter_by_tags(params[:tags])
                .order(published_at: :desc)

    @page_count, @entries = paginate(@entries)
  end

  def show
    @new_comment = @entry.comments.new
    @comments = @entry.comments.persisted
  end

  private
    def set_entry
      @entry = Entry.find_by_slug!(params[:slug])
    end

    def current_page
      @current_page ||= begin
                          page = params[:page].to_i
                          page.positive? ? page : 1
                        end
    end

    def paginate(scope)
      total_count = scope.unscope(:limit, :offset).count
      total_pages = (total_count.to_f / PER_PAGE).ceil

      page = [ current_page, total_pages ].min
      offset = PER_PAGE * (page - 1)

      paginated = scope.limit(PER_PAGE).offset(offset)

      [ total_pages, paginated ]
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
  def pagination(page_count:)
    return if page_count <= 1

    page_links = (1..page_count).map { |page|
      if active_page?(page)
        tag.span page
      else
        link_to page, url_for(request.query_parameters.merge(page:))
      end
    }

    safe_join(page_links, " ")
  end

  private
    # because current_page? is already taken
    def active_page?(page)
      (page == 1 && !params[:page]) ||
      page == params[:page].to_i
    end
end

app/views/admin/entries/_form.html.erb
<%= form_with(model: [:admin, entry]) do |form| %>
  <% if entry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="input-group">
    <%= form.label :slug, style: "display: block" %>
    <%= form.text_field :slug, class: "input" %>
  </div>

  <div class="input-group">
    <%= form.label :published_at, style: "display: block" %>
    <%= form.datetime_field :published_at, class: "input" %>
  </div>

  <div class="input-group">
    <%= form.label :draft, style: "display: block" %>
    <%= form.checkbox :draft %>
  </div>

  <div class="input-group">
    <%= form.label :tags, style: "display: block" %>
    <%= form.collection_checkboxes(:tag_ids, Tag.all, :id, :name) %>
  </div>

  <div class="input-group">
    <%= form.label :body_markdown, style: "display: block" %>
    <%= form.textarea :body_markdown, rows: 10, class: "input" %>
  </div>

  <details class="media-items__entry-form">
    <summary>Media</summary>
      <%= turbo_frame_tag "media-items-page", src: admin_media_items_path(hide_delete: true, target: field_id(Entry, :body_markdown)), loading: "lazy" %>
  </details>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/entries/edit.html.erb
<% content_for :title, "Editing entry" %>

<h1>Editing entry</h1>

<%= render "form", entry: @entry %>

<br />

<%= button_to "Destroy Entry", admin_entry_path(@entry), method: :delete, data: { turbo_confirm: "Are you sure?" } %>

<br />

<div>
  <%= link_to "Show this entry", entry_slug_path(@entry.slug) %>
</div>

app/views/admin/entries/index.html.erb
<% content_for :title, "Admin: Entries" %>

<p><%= link_to "Add entry", new_admin_entry_path %></p>

<table id="entries" class="table">
  <thead>
    <tr>
      <th>Published at</th>
      <th>Title</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td>
          <% if entry.published_at %>
            <%= l entry.published_at, format: :short %>
          <% else %>
            -
          <% end %>
        </td>
        <td><%= link_to entry.title, edit_admin_entry_path(entry) %></td>
        <td><%= entry.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/entries/new.html.erb
<% content_for :title, "New entry" %>

<h1>New entry</h1>

<%= render "form", entry: @entry %>