config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get "admin", to: redirect("admin/entries")
  namespace :admin do
    resources :entries, only: %i[ index new edit create update destroy ]
    resources :media_items, only: %i[ index create destroy ]
    resources :tags
  end

  get "/feed", to: "feeds#show", defaults: { format: "atom" }
  resources :entries, only: %i[ index ] do
    resources :comments, only: %i[ create destroy ], shallow: true
  end
  get "/:slug", to: "entries#show", as: :entry_slug
  resource :session

  # Defines the root path route ("/")
  root "entries#index"
end

app/views/common/_form_errors.html.erb
<% if model.errors.any? %>
  <div style="color: red">
    <ul>
      <% model.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/common/_menu.html.erb
<% if authenticated? && !request.path.starts_with?("/admin") %>
  <div>
    <%= link_to "Admin", admin_path %>
  </div>
<% end %>

<% if request.path.starts_with?("/admin") %>
  <div>
    <%= link_to "Entradas", admin_entries_path %>
    <%= link_to "Etiquetas", admin_tags_path %>
    <%= link_to "Media", admin_media_items_path %>
  </div>
<% end %>

app/views/common/_sidebar.html.erb
<div>
  <h3>Etiquetas</h3>

  <%= form_with(url: entries_path, method: :get) do |form| %>
    <div class="tags-filter">
      <%= form.collection_checkboxes(:tags, Tag.all, :name, :name, include_hidden: false, checked: params[:tags]) do |b| %>
        <%= b.label { b.checkbox + b.text } %>
      <% end %>
    </div>
    <%= form.submit "Filtrar", name: nil %>
  <% end %>
</div>